Feature/chain of responsibility
Makas9/NoOpRunner pull request #52
Opened 2020-12-03 09:31 UTC by gta-6

2020-12-03 13:23 UTC, Kodnot requested changes

2020-12-03 13:23 UTC, Kodnot commented on Client/NoOpRunner.Client/MouseClickHandlers/PlayerHandler.cs
> +                mediaPlayer.Volume = 0.5;
Currently the volume level is not tied to our volume settings, right? How problematic would it be to do so?

2020-12-03 13:23 UTC, Kodnot commented on Core/NoOpRunner.Core/Controls/InputHandlerImplementorPlayerTwo.cs.orig
> +        public InputHandlerImplementorPlayerTwo(PlayerTwo playerTwo)
? Accidental merge artifacts?

2020-12-03 13:24 UTC, Kodnot commented
After you spawn some saws, some new generated powerups may use the saw sprite for some reason

2020-12-07 19:22 UTC, gta-6 commented on Core/NoOpRunner.Core/Controls/InputHandlerImplementorPlayerTwo.cs.orig
> +        public InputHandlerImplementorPlayerTwo(PlayerTwo playerTwo)
Deleted

2020-12-07 20:34 UTC, gta-6 commented
sinkfunny

2020-12-08 09:51 UTC, gta-6 commented
Sprite fixed

2020-12-08 17:42 UTC, Kodnot commented on Core/NoOpRunner.Core/NoOpRunner.Core.csproj
> +    <!-- <Compile Include="Dtos\MediatorMessageDto.cs" /> -->
These can be removed

2020-12-08 17:49 UTC, Kodnot approved these changes

2020-12-08 19:20 UTC, gta-6 commented
Sprites fixed, sound don't care

2020-12-08 19:20 UTC, merged